import path from "node:path";
import { test, expect, type Page } from "@playwright/test";

/**
 * Real, browser-driven proof that the PDF/Canva import flow
 * (docs/pdf-canva-import-plan.md, Stages 1–5) actually RUNS inside a real
 * Next.js server build — not just inside Vitest's module loader.
 *
 * Why this spec exists at all, and why it must never be reduced to a unit
 * test: Stages 1–4 shipped with 375+ passing Vitest tests and a green
 * `next build`, and the feature was still completely broken on this repo's
 * default path. Vitest imports `lib/story/pdf-import.ts` directly in plain
 * Node, so it never exercises Next's bundler; `next build` succeeded because
 * the failure was a *runtime* module-resolution error inside the bundled
 * chunk, only reachable by actually handling a request. The specific bug:
 * a bundler-visible `require.resolve("pdfjs-dist/package.json")` that
 * Turbopack rewrote to its own module identifier instead of a filesystem
 * path (see lib/story/pdf-import.ts#standardFontDataUrl's doc comment and
 * docs/implementation-status.md's 2026-08-18 Turbopack entry).
 *
 * Playwright is the only layer in this repo that runs the real production
 * server (`playwright.config.ts`'s webServer runs `npm run start` against
 * `next build` output), so it is the only layer that can catch this class of
 * bug. Any server-side module with a native, WASM, or self-resolving
 * dependency (pdfjs-dist, @napi-rs/canvas, sharp) needs coverage HERE, not
 * only in Vitest.
 *
 * Test 1 (Phase A only) is the cheap, load-bearing one: it proves the route
 * handler bundles and executes pdfjs-dist + @napi-rs/canvas end to end and
 * returns real rendered pixels. It persists nothing at all — an abandoned
 * Phase A call creates no draft, revision, or media row by design.
 *
 * Test 2 walks the whole picker UI through Phase B, which does create real
 * rows on the linked hosted project — same as e2e/editorial-upload.spec.ts.
 *
 * Requires the SAME fixed editor test account as e2e/editorial-upload.spec.ts
 * (see docs/architecture.md "RLS integration test setup"), loaded from
 * .env.test.local. Skips itself (not a hard failure) if those credentials
 * aren't present, matching that spec's pattern exactly.
 *
 * Fixture hygiene: Test 2's draft is titled `e2e-pdf-import-<runid>` and its
 * contributor `E2E PDF Import Contributor <runid>`, both registered in
 * scripts/cleanup-editorial-e2e-fixtures.mjs's scoping prefixes.
 */

try {
  process.loadEnvFile(path.join(__dirname, "..", ".env.test.local"));
} catch {
  // File doesn't exist in this environment -- the tests below skip themselves.
}

const EDITOR_EMAIL = process.env.SUPABASE_RLS_TEST_EDITOR_EMAIL;
const EDITOR_PASSWORD = process.env.SUPABASE_RLS_TEST_EDITOR_PASSWORD;
const hasEditorCredentials = Boolean(EDITOR_EMAIL && EDITOR_PASSWORD);

// The same committed two-page fixture lib/story/pdf-import.test.ts uses
// (generated by scripts/generate-pdf-import-fixtures.mjs; fictional content
// only, per Engineering Rule 22).
const FIXTURE_PDF = path.join(
  __dirname,
  "..",
  "lib",
  "story",
  "__fixtures__",
  "valid-two-page.pdf",
);

/**
 * Every locator below is scoped to <main>, never the whole page.
 *
 * That is not stylistic: components/site-header.tsx renders an always-mounted
 * (`display:none` when closed) <dialog> containing the very same SignInForm /
 * SignUpForm components the real /sign-in and /sign-up pages render. So on
 * ANY page, an unscoped `page.getByLabel("Email" | "Password" | "Display
 * name")` also matches the header modal's hidden copy — which, because
 * SignInForm hard-codes id="email"/id="password", currently wins the
 * `label[for=...]` lookup and resolves to an invisible element that can never
 * be filled. Scoping to <main> makes these locators unambiguous regardless of
 * how that header modal is later fixed.
 *
 * The rest of e2e/ predates that header and still uses unscoped locators —
 * see docs/implementation-status.md's 2026-08-18 Turbopack entry, which flags
 * that as a separate, pre-existing regression.
 */
function mainOf(page: Page) {
  return page.getByRole("main");
}

async function signInAsEditorAndOpenPdfMode(page: Page) {
  await page.goto("/sign-in");
  const signIn = mainOf(page);
  await signIn.getByLabel("Email").fill(EDITOR_EMAIL!);
  await signIn.getByLabel("Password").fill(EDITOR_PASSWORD!);
  await signIn.getByRole("button", { name: "Sign in" }).click();
  await page.waitForURL((url) => !url.pathname.startsWith("/sign-in"));

  await page.goto("/editorial/new");
  await mainOf(page).getByLabel("PDF / Canva file").check();
}

test.describe("PDF/Canva import (real Route Handlers, real Next server)", () => {
  test.skip(
    !hasEditorCredentials,
    "Requires SUPABASE_RLS_TEST_EDITOR_EMAIL/PASSWORD in .env.test.local — see docs/architecture.md 'RLS integration test setup'.",
  );

  test("Phase A renders real page thumbnails through the bundled route handler", async ({
    page,
  }) => {
    await signInAsEditorAndOpenPdfMode(page);
    const main = mainOf(page);

    await main.locator("#pdf-import-file").setInputFiles(FIXTURE_PDF);

    // Assert on the real HTTP response, not only the rendered UI: the bug
    // this spec exists for produced a 400/500 from this exact route while
    // every unit test stayed green.
    const [response] = await Promise.all([
      page.waitForResponse(
        (r) =>
          r.url().includes("/editorial/new/pdf-preview") &&
          r.request().method() === "POST",
        { timeout: 60000 },
      ),
      main.getByRole("button", { name: "Upload & preview pages" }).click(),
    ]);

    expect(response.status()).toBe(200);
    const body = (await response.json()) as {
      pageCount: number;
      pages: {
        pageNumber: number;
        width: number;
        height: number;
        dataUrl: string;
      }[];
    };
    expect(body.pageCount).toBe(2);
    expect(body.pages).toHaveLength(2);
    for (const renderedPage of body.pages) {
      expect(renderedPage.dataUrl.startsWith("data:image/png;base64,")).toBe(
        true,
      );
      // Real rasterized page, not a 1x1 placeholder or an empty string:
      // the fixture's pages render at ~20KB of PNG each (~28KB base64).
      expect(renderedPage.dataUrl.length).toBeGreaterThan(5000);
      expect(renderedPage.width).toBeGreaterThan(100);
      expect(renderedPage.height).toBeGreaterThan(100);
    }

    // ...and that the browser can actually decode what the server sent —
    // a truncated/corrupt data URL would still satisfy the length check
    // above but fail to paint.
    const thumbnails = main.locator("ul img");
    await expect(thumbnails).toHaveCount(2);
    for (let i = 0; i < 2; i++) {
      await expect
        .poll(
          () =>
            thumbnails
              .nth(i)
              .evaluate((img) => (img as HTMLImageElement).naturalWidth),
          { timeout: 15000 },
        )
        .toBeGreaterThan(100);
    }
  });

  test("editor imports a PDF end to end and lands in the editor with both pages attached", async ({
    page,
  }) => {
    const runId = Math.random().toString(36).slice(2, 8);

    await signInAsEditorAndOpenPdfMode(page);
    const main = mainOf(page);

    await main.getByLabel("Title").fill(`e2e-pdf-import-${runId}`);
    await main.getByLabel("New (unlinked) contributor").check();
    await main
      .getByLabel("Display name")
      .fill(`E2E PDF Import Contributor ${runId}`);

    await main.locator("#pdf-import-file").setInputFiles(FIXTURE_PDF);
    await main.getByRole("button", { name: "Upload & preview pages" }).click();

    await expect(main.getByRole("button", { name: /^Page 1/ })).toBeVisible({
      timeout: 60000,
    });
    await main.getByRole("button", { name: /^Page 1/ }).click();
    await main.getByRole("button", { name: /^Page 2/ }).click();
    await expect(main.getByText("2 of 12 selected")).toBeVisible();

    await main
      .getByLabel("Alt text for page 1 (required)")
      .fill("First page of the e2e fixture PDF");
    await main
      .getByLabel("Alt text for page 2 (required)")
      .fill("Second page of the e2e fixture PDF");

    const submit = main.getByRole("button", { name: "Create Import Draft" });
    await expect(submit).toBeEnabled();

    const [attachResponse] = await Promise.all([
      page.waitForResponse(
        (r) =>
          r.url().includes("/editorial/new/pdf-attach") &&
          r.request().method() === "POST",
        { timeout: 120000 },
      ),
      submit.click(),
    ]);
    expect(attachResponse.status()).toBe(200);

    await page.waitForURL(/\/editorial\/[^/]+\/edit$/, { timeout: 30000 });

    // Stage 3's placeholder body text — the "mandatory review step" signal
    // that this draft still needs real narrative text written.
    const editor = mainOf(page);
    await expect(
      editor.getByText("Imported from PDF — add your story text here.").first(),
    ).toBeVisible({ timeout: 30000 });
    // Both rendered pages went through the real image pipeline
    // (private bucket -> processStoryMedia -> signed URL).
    await expect(editor.getByText(/Images \(2\)/)).toBeVisible({
      timeout: 30000,
    });
  });
});
